---
title: "Project 1"
author: "John W. Hoggard"
date: "2020-09-22"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Project 1 will consist of an exploratory data analysis of the data set you chose earlier.

You need to have three files in your repository (although you may have others, if you wish):

* The data set you chose.
* A script, `CleanData.R`, which completes the steps needed to load and clean your data.  This will allow someone else (like your professor) to automatically perform your first loading and cleaning steps on the data.  (You can run this from your RMarkdown document using `source(CleanData.R)`, if it is in the same directory.)
* A report, written in RMarkdown, which will cover the points below.

Make sure your commit to be graded is pushed to GitLab by the end of **Friday, October 2.**.

---

1. First, get your data loaded into R.  Start the `CleanData.R` file by loading the data. (I recommend having the data file in the current directory.)

    In your report, include a section "Loading and Cleaning the Data", in which you briefly describe the process, including any unusual choices you made about modifying or cleaning data in the file you obtained.
    
    In particular, was there any "messy" data that you had to deal with?  Did you identify any missing (`NA`) values?  Is there any clearly (or possibly) incorrect data in your data set, and if so, how did you choose to deal with it?  All preparatory loading and cleaning should be carried out by this file.
    
    This section (and the `CleanData.R` file) will naturally grow and change as you work on your report.
  
2. In a section of your report, briefly describe the data set.  Explain what it measures, how it was collected (if that information is available), how many rows there are, and provide a description of any columns you intend to make use of.  (You may include questions you cannot answer; it is sometimes the case that we don't know for sure what raw data from someone else represents.  But include your best guesses.)  
    
2. Explore the data by individual variables.  If there are missing values or bad data, identify and deal with them.  (Remember to add these to your `CleanData.R` script, and to your "Loading and Cleaning" section.)

    Include in your report a more detailed analysis of at least two different variables in your data set.  In this analysis, include:
     a. Something interesting you found in the data set.  (You may have to explore your data set for a while, but "interesting" is loosely defined here.)
     b. At least one graph generated by `ggplot` and at least one table generated by `dplyr`.
     c. If your data set includes both categorical and numerical variables, include at least one of each in your analysis as well.
3. Explore the interactions of variables in your data set.  Report on one interesting relationship you believe you found between at least two variables in your data set.  (It is your choice how you explore and represent this relationship.)
4. Include a brief conclusion.  Indicate currently remaining questions and some other possible avenues for further exploration, including possible additional data you would like to obtain.

A few final notes:

* As you work, you may find more examples of bad data values you wish to remove or change. Edit the "Loading and Cleaning the Data" section of your report, and update your `CleanData.R` as you find these changes.  (If you are making changes, it might be a good idea to re-run your script to make sure you are looking at the data set using the correct processing.)
* This is fairly open-ended, and should be driven by some questions you might have about your data set.  See your professor if you are struggling for ideas.
* You may feel free to consult any sources you wish. If you take anything significant from a source, cite it in your report.  (Rather than a proper Bibliography, you can just cite directly in the text.)